config/routes.rb
Rails.application.routes.draw do
  get 's3/sign'

  get 'products/index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :recipe
  resources :catalogs
  resources :users

  get 'home/index'

  root 'sessions#new'
end

app/models/catalog.rb
class Catalog < ApplicationRecord
  belongs_to :user
  has_many :recipes
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  before_action :set_catalog, only: %i[show edit update destroy]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :correct_user, only: :show
  before_action :admin_user, except: :show

  # GET /catalogs
  # GET /catalogs.json
  def index
    @catalogs = Catalog.all
  end

  # GET /catalogs/1
  # GET /catalogs/1.json
  def show; end

  # GET /catalogs/new
  def new
    @catalog = Catalog.new
  end

  # GET /catalogs/1/edit
  def edit; end

  # POST /catalogs
  # POST /catalogs.json
  def create
    @catalog = Catalog.new(catalog_params)

    respond_to do |format|
      if @catalog.save
        format.html { redirect_to @catalog, notice: 'Catalog was successfully created.' }
        format.json { render :show, status: :created, location: @catalog }
      else
        format.html { render :new }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catalogs/1
  # PATCH/PUT /catalogs/1.json
  def update
    respond_to do |format|
      if @catalog.update(catalog_params)
        format.html { redirect_to @catalog, notice: 'Catalog was successfully updated.' }
        format.json { render :show, status: :ok, location: @catalog }
      else
        format.html { render :edit }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogs/1
  # DELETE /catalogs/1.json
  def destroy
    @catalog.destroy
    respond_to do |format|
      format.html { redirect_to catalogs_url, notice: 'Catalog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_catalog
    @catalog = Catalog.find_by(id: params[:id])
  end

  def set_user
    @user = @catalog && @catalog.user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def catalog_params
    params.fetch(:catalog, {})
  end
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/views/catalogs/_form.html.haml
= form_with(model: catalog, local: true) do |form|
  - if catalog.errors.any?
    #error_explanation
      %h2
        = pluralize(catalog.errors.count, "error")
        prohibited this catalog from being saved:
      %ul
        - catalog.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/catalogs/edit.html.haml
%h1 Editing Catalog
= render 'form', catalog: @catalog
= link_to 'Show', @catalog
|
= link_to 'Back', catalogs_path

app/views/catalogs/index.html.haml
%p#notice= notice
%h1 Catalogs
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @catalogs.each do |catalog|
      %tr
        %td= link_to 'Show', catalog
        -#%td= link_to 'Edit', edit_catalog_path(catalog)
        -#%td= link_to 'Destroy', catalog, method: :delete, data: { confirm: 'Are you sure?' }
%br/
-#= link_to 'New Catalog', new_catalog_path

app/views/catalogs/new.html.haml
%h1 New Catalog
= render 'form', catalog: @catalog
= link_to 'Back', catalogs_path

app/views/catalogs/show.html.haml
.row
  .col-md-3.col-md-offset-3.container
    .text-center
      %h1 My Recipes
      = link_to 'Add a new Recipe', new_recipe_path
#cards_container.container{data: raw(@catalog.recipes.to_json)}