config/routes.rb
Rails.application.routes.draw do
  get 's3/sign'

  get 'products/index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :recipe
  resources :catalogs
  resources :users

  get 'home/index'

  root 'sessions#new'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :catalog
  has_many :ingredients, autosave: true, dependent: :destroy
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :correct_user, except: %i[new create]

  def new
    @recipe = Recipe.new
    ingredient = Ingredient.new
    ingredient.product = Product.new
    @recipe.ingredients << ingredient
    @recipe
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.catalog = current_user.catalog
    respond_to do |format|
      if @recipe.save # TODO: logic above should be reviewed
        format.html { redirect_to @recipe.catalog, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe.catalog }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /recipe/1/edit
  def edit; end

  # PATCH/PUT /recipe/1
  # PATCH/PUT /recipe/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe/1
  # DELETE /recipe/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to @recipe.catalog, notice: 'Recipe was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def recipe_params
    recipe_params = params.require(:recipe).permit(:name, :id, :description, :short_description, :image_url,
                                                   { ingredient: %i[id weight] },
                                                   product: %i[id name caloricity])
    ingredients = combine_ingredients recipe_params.to_h
    { short_description: recipe_params[:short_description], description: recipe_params[:description],
      name: recipe_params[:name], ingredients: ingredients, caloricity: caloricity(ingredients),
      image_url: recipe_params[:image_url] }
  end

  private

  def combine_ingredients(params)
    format_params! params
    params[:ingredient].each_with_index.with_object([]) do |(ingredient_params, i), ingredients|
      next unless ingredient_params[:weight].present? && params[:product][i].present? &&
                  params[:product][i][:caloricity].present?
      ingredients << combine_ingredient(ingredient_params, params, i)
    end
  end

  def combine_ingredient(ingredient_params, params, index)
    if ingredient_params[:id].present? # update ingredient
      update_ingredient(ingredient_params, params, index)
      # new ingredient
    elsif params[:product][index][:id].present? && (product = Product.find_by(id: params[:product][index][:id])) &&
          (params[:product][index].to_a - product.attributes.to_a).empty? # full prod match
      new_ingredient_with_product(ingredient_params, product)
    else
      new_ingredient(ingredient_params, params, index)
    end
  end

  def new_ingredient_with_product(ingredient_params, product)
    ingredient = Ingredient.new
    ingredient.weight = ingredient_params[:weight]
    ingredient.product = product
    ingredient
  end

  def new_ingredient(ingredient_params, params, index)
    product = Product.new(params[:product][index].reject { |k| k == 'id' })
    ingredient = Ingredient.new(ingredient_params.reject { |k| k == 'id' })
    ingredient.product = product
    ingredient
  end

  # TODO: else raise some exception
  def update_ingredient(ingredient_params, params, index)
    ingredient = @recipe.ingredients.find_by(id: ingredient_params[:id])
    return unless ingredient # edit existent ingredient
    ingredient.weight = ingredient_params[:weight]
    if (params[:product][index].to_a - ingredient.product.attributes.to_a).any?
      # new product instead of change of the old one
      ingredient.product = Product.new(params[:product][index].reject { |k| k == 'id' })
    end
    ingredient
  end

  def format_params!(params)
    params[:ingredient].each_with_index do |ingredient, i|
      ingredient_to_update = params[:ingredient][i]
      ingredient_to_update[:weight] = ingredient[:weight].to_f
      ingredient_to_update[:id] = ingredient[:id].to_i if ingredient_to_update[:id].present?
    end
    params[:product].each_with_index do |product, i|
      product_to_update = params[:product][i]
      product_to_update[:caloricity] = product[:caloricity].to_f
      product_to_update[:id] = product[:id].to_i if product_to_update[:id].present?
    end
  end

  def set_recipe
    @recipe = Recipe.find_by(id: params[:id])
  end

  def set_user
    @user = @recipe && @recipe.catalog.user
  end

  def caloricity(ingredients)
    result = ingredients.each.with_object(weight: 0, caloricity: 0) do |i, total|
      total[:weight] += i.weight
      total[:caloricity] += i.weight * i.product.caloricity
    end
    (result[:caloricity] / result[:weight]).round(2)
  end
end

app/helpers/recipe_helper.rb
module RecipeHelper
  def dummy_ingredient
    Ingredient.new(product: Product.new)
  end
end

app/views/recipe/_form.html.haml
.row
  .container
    = form_for @recipe, url: {action: content_for(:action)}, html: { class: 'form-recipe' } do |f|
      .row
        %h2.form-recipe-heading.text-center.col-md-12= content_for(:header)
      .row
        .col-md-offset-4.col-md-4
        .form-group.col-md-4
          = f.label :name, class: 'sr-only'
          = f.text_field :name, class: 'form-control', placeholder: 'Recipe name', required: true, autofocus: true, id: :first
      .row
        .col-md-offset-3.col-md-3
        .form-group.col-md-6
          = f.label :short_description
          = f.text_area :short_description, class: 'form-control', rows: 3, maxlength: 150, placeholder: 'short description'

      .row
        .col
          #search_container.mb-2
        .col
          #recipe_image_uploader{data: {name: 'recipe[image_url]', value: @recipe.image_url}}
      #ingredients
        - @recipe.ingredients.each_with_index do |ingredient, i|
          - style = i == 0 && @recipe.ingredients.size == 1 ? 'display:none;' : 'display:block;'
          = render partial: 'recipe/ingredient', locals: { ingredient: ingredient, recipe_form: f, style: style }
      .row.mt-4
        .col
          = link_to 'javascript:function()', id: 'add_new_ingredient' do
            %i.fa.fa-plus.fa-2x.text-success.pull-right.top-aligned-row
      .row.mb-2
        .col
          = f.label :description
          = f.text_area :description, class: 'form-control', rows: 5, placeholder: 'description'
      .form-group.col-md-12.text-center
        = f.submit class: 'btn btn-lg btn-primary'
-#TODO really controversial solution, should be fully refactored
= form_for @recipe, url: 'dummy-url', html: {style: 'display:none;', class: 'dummy-form'} do |f|
  #new_ingredient
    = render partial: 'recipe/ingredient', locals: {ingredient: dummy_ingredient, recipe_form: f, style: nil}

app/views/recipe/_ingredient.html.haml
= recipe_form.fields_for ingredient, index: nil do |ingredient_form|
  %div.ingredient
    %label
      %b Ingredient
    .row
      = render partial: 'recipe/product', locals: { product: ingredient.product, recipe_form: recipe_form }
      .form-group.col-md-4.col-sm-12
        = ingredient_form.label :weight, 'Weight, g'
        = ingredient_form.text_field :weight, class: 'form-control ingredient-weight', required: true, autocomplete: 'off', placeholder: 'weight', type: :number, step: :any, min: 0
        = ingredient_form.hidden_field :id, value: ingredient.id
    .row
      .col
        = link_to 'javascript:function()', onclick: 'removeIngredient($(this))', class: 'remove-ingredient', style: style do
          %i.fa.fa-minus.fa-2x.pull-right{style: 'color:red'}

app/views/recipe/_product.html.haml
= recipe_form.fields_for(product, index: nil) do |product_form|
  .form-group.col-md-4.col-sm-12
    = product_form.label :name
    = product_form.text_field :name, class: 'form-control product-name', required: true, autocomplete: 'off', placeholder: 'name'
  .form-group.col-md-4.col-sm-12
    = product_form.label :caloricity, 'Caloricity, kcal/100g'
    = product_form.text_field :caloricity, class: 'form-control product-caloricity', required: true, autocomplete: 'off', placeholder: 'caloricity', type: :number, step: :any, min: 0
    = product_form.hidden_field :id, class: 'product-id', value: product.id

app/views/recipe/_recipe.html.haml
.row
  .col.col-auto
    %h1= recipe.name
  .col
    %div.recipe-actions
      = link_to @recipe.catalog, class: 'mr-3', title: 'Back' do
        %i.fa.fa-long-arrow-left
      = link_to edit_recipe_path(@recipe), class: 'mr-3', title: 'Edit' do
        %i.fa.fa-pencil
      = link_to 'javascript:function()', id: 'delete_recipe', title: 'Delete' do
        %i.fa.fa-trash-o

%div.collapse{id: "recipe_details_#{recipe.id}", class: params[:controller] == 'recipe' ? 'show' : '' }
  .row
    .col-sm-12.col-md-6
      .lead= recipe.short_description
      %img.w-100{src: recipe.image_url.present? ? recipe.image_url : '/placeholder-400x300.png', alt: 'No picture found'}
    .col-sm-12.col-md-6
      %h2 Ingredients
      %table.table.table-striped.lead.ingredients-table
        %thead
          %tr
            %th.col Name
            %th.col Weight,g
            %th.col kcal/100g
        %tbody
          - recipe.ingredients.each do |i|
            %tr
              %td.ingredient-word-breaks= i.product.name
              %td= i.weight
              %td= i.product.caloricity
          %tr
            %td
              %h4 Total
            %td= recipe.ingredients.inject(0) { |sum, i| sum + i.weight }
            %td
              %h4= recipe.caloricity
  .row
    .col
      %p.recipe-description.lead= recipe.description

app/views/recipe/create.html.haml
%h1 Recipe#create
%p Find me in app/views/recipe/create.html.erb

app/views/recipe/edit.html.haml
- provide :header, 'Edit Recipe'
- provide :action, :update
= render 'form'

app/views/recipe/new.html.haml
- provide :header, 'Add a new Recipe'
- provide :action, :create
= render 'form'

app/views/recipe/show.html.haml
=render partial: 'recipe/recipe', locals: { recipe: @recipe }
%div#recipe_data{data: {recipe: @recipe.to_json}}