config/routes.rb
Rails.application.routes.draw do
  get 's3/sign'

  get 'products/index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :recipe
  resources :catalogs
  resources :users

  get 'home/index'

  root 'sessions#new'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate!, except: %i[new create]
  include SessionsHelper

  private

  def admin_user
    redirect_to(root_url) unless current_user_admin?
  end

  def correct_user
    redirect_to(root_url) if !current_user?(@user) && !current_user_admin?
  end

  def authenticate!
    return if logged_in?
    store_location
    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.haml
%nav.navbar.navbar-inverse.bg-inverse.navbar-toggleable-sm.sticky-top
  -if logged_in?
    %button.navbar-toggler.navbar-toggler-right{'data-toggle': 'collapse', 'data-target': '#navbarText'}
      %span.navbar-toggler-icon
  =link_to 'Cookery Book', root_path, class: 'navbar-brand nav-item'
  -if logged_in?
    %div.navbar-collapse.collapse{id: 'navbarText'}
      %ul.nav.navbar-nav.ml-auto
        %li.dropdown
          %a.dropdown-toggle.nav-link{href: '#', 'data-toggle': 'dropdown'}
            My Account
            %span.caret
          %ul.dropdown-menu.bg-inverse.header-dropdown
            %li
              =link_to 'Settings', edit_user_path(current_user), class: 'nav-link'
            %li
              =link_to 'Sign out', logout_path, method: :delete, class: 'nav-link'